### ISSUE TITLE
Flexicontent compatibility

### ISSUE THREAD

**Issue by micker** [OSTraining/OSMap#6]
FLEXIcontent have his xmap plugin
http://www.flexicontent.org/downloads/extensions/64-extension-specific/134-xmap-plugin-for-flexicontent.html
what do you prefer, adding in osmap and github
and flexicontent team add pull request on it ?
or stay deconnect ?

**Comment by andergmartins** [comment]
Hi @micker,

The flexicontent team and anyone else is very welcome to submit Pull Requests :) We would appreciate that! But it requires to move its plugin to the group **osmap** instead of **xmap**.
But despite of the fact we had to create a new plugin group, we will making sure OSMap is compatible with XMap plugins without any rewrite.

**Comment by andergmartins** [comment]
Hi @micker,

The flexicontent team and anyone else is very welcome to submit Pull Requests :) We would appreciate that! We are making sure to be fully compatible with XMap plugins.

**Comment by stevejburge** [comment]
So it's fine to use the xmap group for now. Over time, we'll encourage plugin to use osmap, but that will be later.

**Comment by andergmartins** [comment]
I'm closing this since it is already published as an OSMap plugin and listed here: https://www.alledia.com/docs/osmap/plugins/
