### ISSUE TITLE
Choose plugins during install

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSMap#81]
[feedback]
You integrate many plugins XMAP, no application choice, then we must remove unnecessary plugins. I suggest to offer a choice during installation
[/feedback]
https://secure.helpscout.net/conversation/94469140/12766/

**Comment by htmgarcia** [comment]
A shorter solution could be adding a link pointing to OSmap plugins in the install details with a standout text explaining you can choose which plugins to enable.
![warning](https://cloud.githubusercontent.com/assets/4999794/7963076/792927b0-09d6-11e5-88e2-d8129c04d784.png)
Of course, using better words :)

**Comment by andergmartins** [comment]
Thanks @htmgarcia, that makes things easier. In addition to that, I will add a conditional to the installer to just enable the plugin if the required component is installed. 

I would prefer do not install, instead of just not publish it. But that would force users to re-install OSMap if K2 was installed after OSMap, because those plugins are only available on the main package. We would need to have separated packages for each plugin.

I agree about go with a quick solution for now. We can improve that later.

**Comment by htmgarcia** [comment]
> I will add a conditional to the installer to just enable the plugin if the required component is installed. 
+1!

**Comment by andergmartins** [comment]
Fixed in 70a3e6c9 and 886112d3.
This is available now in the installer for the other Alledia extensions, here: https://github.com/OSTraining/AllediaInstaller/commit/cee2e016e6d96386443be53758133db2c0710869

**Comment by htmgarcia** [comment]
Very nice!
```publish="com_k2=*"```

**Comment by andergmartins** [comment]
:) Cool
Bill suggested change from "=" to ":", so now it is:
   
    publish="com_k2:*"
